export const ADD_PRODUCTS_BASKET = 'ADD_PRODUCTS_BASKET';
export const GET_NUMBERS_BASKET = 'GET_NUMBERS_BASKET';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
